name: shopfirst
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  cupertino_icons: ^1.0.2
  build_runner: ^2.4.6
  dio: ^5.3.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  shimmer: ^3.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  carousel_slider: ^4.2.1
  firebase_database: ^10.2.4
  json_annotation: ^4.8.1
  uuid: ^3.0.7
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  restart_app: ^1.2.1
  google_sign_in: ^6.1.4



dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/Logo/Minimalist Happy Shopping Logo.png


